config/routes.rb
GermanLernen::Application.routes.draw do
  root to: "sessions#new"

  resources :quizzes, only: [:index]
  match 'quizzes/der_die_das', to: 'quizzes#der_die_das'#, as: 'der_die_das_quiz'
  match 'quizzes/translate_noun', to: 'quizzes#translate_noun'#, as: 'translate_noun_quiz'
  match 'quizzes/pluralise', to: 'quizzes#pluralise'
  #match 'quizzes/random_sentence', to: 'quizzes#random_sentence', as: 'random_sentence_quiz'
  

  #resources :sentences, except: :new #, only: [:index, :edit, :update, :destroy, :create]
  resources :verbs, except: [:edit]
  resources :nouns, except: [:edit]
  resources :users
  resources :password_resets, except: [:show, :delete]
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  
  include QuizzesHelper

  before_filter :signed_in_user
  before_filter :hint
  before_filter :check_order, only: [:random_sentence, :translate_noun]
  before_filter :current_noun, except: [:index]
  before_filter :set_category, except: [:index]

  def index
  end

  def translate_noun
    @correct = !@noun.nil? && 
              ((@order == "de_to_en" && params[:answer] == @noun.english) ||
              (@order == "en_to_de" && params[:answer] == @noun.german))
    @noun = Noun.random if @noun.nil? || @correct
    respond_to do |format|
      format.html
      #format.js
    end
  end

  def der_die_das
    @definite_nominative_articles = ["der", "die", "das"]
    @correct = !@noun.nil? && @noun.article.nominative == params[:commit]
    @noun = Noun.random(@category) if @noun.nil? || @correct
    set_prev_answers
    respond_to do |format|
      format.html
      format.js { render :update_with_prev_answer_buttons }
    end
  end

  def pluralise
    @correct = !@noun.nil? && @noun.pluralisation_rule.rule == params[:commit]
    @noun = Noun.random(@category) if @noun.nil? || @correct
    set_prev_answers
    respond_to do |format|
      format.html
      format.js { render :update_with_prev_answer_buttons }
    end
  end

  private
    def current_noun
      @noun = Noun.where(id: params[:noun_id]).first
    end

    def hint
      redirect_to :index if params[:commit] == "Hint"
    end

    def check_order
      @is_random = !orders.include?(params[:order])
      @order = @is_random ? orders[rand(orders.count())] : params[:order]
    end

    def orders
      ["en_to_de", "de_to_en"]
    end

    def set_prev_answers
      params[:prev_answers] ||= []
      @prev_answers = @correct ? [] : params[:prev_answers]
      @prev_answers << params[:commit] unless @correct \
        || params[:commit].nil? || @prev_answers.include?(params[:commit])
    end

    def set_category
      @category = params[:category_id] \
                      ? Category.where(id: params[:category_id]).first \
                      : categories_of_type(Noun).first
    end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
  def label_from(obj)
    @order == "en_to_de" ? obj.english : obj.german
  end

  def show_plural?
    !@noun.plural.blank? && @order == "de_to_en"
  end

  def show_literal?
  	!@sentence.literal_translation.blank? && @order == "en_to_de"
  end

  def from_lang
    @order == "en_to_de" ? "english" : "german"
  end

  def to_lang
    @order == "en_to_de" ? "german" : "english"
  end

  def correct_answer(obj)
  	@order == "en_to_de" ? obj.german : obj.english
  end

  def categories_of_type(type)
    Category.includes(:categorisations).where(categorisations: { sentence_part_type: type })
  end
end

app/views/quizzes/_noun_q.html.erb
<% quiz_item = @noun %>

<h3>Translate from <%= from_lang %> to <%= to_lang %></h3>

<% if @correct %>

<% end %>
<%= form_tag(:quizzes_translate_noun, remote: false) do %>
  <%= label_tag "answer" do %>
    <strong id="noun_from"><%= label_from(@noun) %></strong>
    <small id="noun_plural"><%= "(#{@noun.plural})" if show_plural? %></small>
    <%= button_tag('notes', 
                   type: 'button', 
                   class: "btn btn-mini btn-link toggle collapsed", 
                   disabled: @noun.notes.blank?, 
                   data: { toggle: "collapse", target: "#noun_notes" })  %>
  <% end %>
  <%= text_field_tag "answer", "", 
                     placeholder: "Translate to #{to_lang}",
                     autocomplete: :off, autofocus: :true %>
  <div id="noun_notes" class="collapse"><%= @noun.notes %></div>
  <%= hidden_field_tag "noun_id", @noun.id %>
  <%= hidden_field_tag "order", @order %>
  <div class="actions">
    <%= submit_tag "Submit", class: "btn btn-primary submit-answer" %>
<!--     <%= submit_tag "Hint", class: "btn btn-small request-hint" %>
    <%= button_tag "Skip", class: "btn btn-small" %> -->
  </div>
<% end %>

<div id="hint">

</div>

app/views/quizzes/_sentence_q.html.erb
<% params = !@is_random ? { order: @order } : {} %>
<%= form_tag({ controller: "quizzes", action: "random_sentence", params: params }, remote: true) do %>
  <%= label_tag "answer" do %>
  	<strong id="sentence_from"><%= label_from(@sentence) %></strong>
  	<small id="sentence_literal"><%= "(#{@sentence.literal_translation})" if show_literal? %></small>
  	<%= button_tag('notes', 
                   type: 'button', 
  				         class: "btn btn-mini btn-link toggle collapsed", 
  	               disabled: @sentence.notes.blank?, 
  	               data: { toggle: "collapse", target: "#sentence_notes" })  %>
  <% end %>
  <%= text_field_tag "answer", "", 
                     placeholder: translation_placeholder, 
                     autocomplete: :off, autofocus: :true %>
  <div id="sentence_notes" class="collapse"><%= @sentence.notes %></div>
  <%= hidden_field_tag "correct_answer", correct_answer(@sentence) %>

  <div class="actions">
    <%= submit_tag "Submit", class: "btn btn-primary submit-answer" %>
    <%= submit_tag "Hint", class: "btn btn-small request-hint" %>
    <%= button_tag "Skip", class: "btn btn-small" %>
  </div>
<% end %>

<div id="hint">

</div>

app/views/quizzes/der_die_das.html.erb
<div class="row">
  <div class="span8 offset2">
    <%= form_tag(:quizzes_pluralise, remote: false, method: :get, id: "category_form") do %>
    <%= select_tag :category_id, options_from_collection_for_select(categories_of_type(:Noun), :id, :name_and_count_noun, @category.id) %>
  <% end %>
    <h2 id="noun_text" title="<%= @noun.english %>"><%= @noun.german %></h2>
    <%= form_tag(:quizzes_der_die_das, remote: true, class: "ddd_form") do %>
      <%= hidden_field_tag :noun_id, @noun.id, id: "noun_id" %> 
      <% @prev_answers.each do |a| %>
        <%= hidden_field_tag "prev_answers[]", a, class: "prev_answer", id: "prev_answer_" + a %>
      <% end %>
      <% @definite_nominative_articles.each do |a| %>
        <% disabled = @prev_answers.include?(a) 
           btn_cls = disabled ? "btn-danger" : "btn-info" %>
        <%= submit_tag a, class: "submit btn #{btn_cls}", disabled: disabled %>
      <% end %>
      <%= hidden_field_tag :category_id, @category.id %>
    <% end %>
  </div>
  <div class="span2"/>
</div>

app/views/quizzes/index.html.erb
<h3>Noun Quizzes</h3>
<ul>
  <li><%= link_to 'Der, die, oder das?', quizzes_der_die_das_path %></li>
  <li><%= link_to 'Pluralise', quizzes_pluralise_path %></li>
  <!-- <li><%= link_to 'Translate DE -> EN', quizzes_translate_noun_path, order: :de_to_en %></li>
  <li><%= link_to 'Translate EN -> DE', quizzes_translate_noun_path, order: :en_to_de %></li> -->
</ul>

app/views/quizzes/pluralise.html.erb
<div class="row"> 
  <div id="question" class="span6 offset2">
  <%= form_tag(:quizzes_pluralise, remote: false, method: :get, id: "category_form") do %>
    <%= select_tag :category_id, options_from_collection_for_select(categories_of_type(:Noun), :id, :name_and_count_noun, @category.id) %>
  <% end %>
    <h2 id="noun_text" title="<%= @noun.english %>"><%= @noun.german %></h2>
    <%= form_tag(:quizzes_pluralise, remote: true) do %>
      <%= hidden_field_tag :noun_id, @noun.id, id: "noun_id" %> 
      <% @prev_answers.each do |a| %>
        <%= hidden_field_tag "prev_answers[]", a, class: "prev_answer", id: "prev_answer_" + a %>
      <% end %>
      <% PluralisationRule.all.each do |pr| %>
        <% disabled = @prev_answers.include?(pr.rule) 
           btn_cls = disabled ? "btn-danger" : "btn-info" %>
        <%= submit_tag pr.rule, class: "submit btn #{btn_cls}", disabled: disabled %>
      <% end %>
      <%= hidden_field_tag :category_id, @category.id %>
    <% end %>
  </div>
  <div class="span4">
    
  </div>
</div>

app/views/quizzes/random_sentence.html.erb
<div class="row"> 
  <div id="question" class="span8 offset2">
  	<!-- <%= render 'shared/german_chars' %> -->
    <%= render 'sentence_q' %>
  </div>
  <div class="span2">
    
  </div>
</div>

app/views/quizzes/random_sentence.js.erb
$("#question").fadeOut('fast', function() {
  $(this).html("<%= escape_javascript(render('sentence_q')) %>").fadeIn('fast');
});
$("#answer").focus();

app/views/quizzes/translate_noun.html.erb
<div class="row"> 
  <div id="question" class="span8 offset2">
    <%= render 'noun_q' %>
  </div>
  <div class="span2">
    
  </div>
</div>

app/views/quizzes/translate_noun.js.erb
$("#question").fadeOut('fast', function() {
  $(this).html("<%= escape_javascript(render('noun_q')) %>").fadeIn('fast');
});
$("#answer").focus();

app/views/quizzes/update_with_prev_answer_buttons.js.erb
<% if @correct %>
  $("#noun_text").fadeOut('fast', function() {
    $(this).prop('title', "<%= @noun.english %>")
    $(this).text("<%= @noun.german %>").fadeIn('fast');
  }); 

  $("#noun_id").val(<%= @noun.id %>);
  $("[name*=prev_answer]").remove();
  var btns = $(".submit");
  toggle_class(btns, "btn-danger", "btn-info");
  btns.prop('disabled', false);
<% else %>
  var form_div = $(".ddd_form > div");
  <% @prev_answers.each do |a| %>
    var btn = $(".submit[value=<%= a %>]");
    toggle_class(btn, "btn-info", "btn-danger");
    btn.prop('disabled', true);

    var hidden_ans = $("#prev_answer_<%= a %>");
    if (hidden_ans.get(0) == null) {
      form_div.append("<%= escape_javascript(hidden_field_tag('prev_answer[]', a, id: 'prev_answer_' + a)) %>");
    }
  <% end %>
<% end %>