config/routes.rb
GermanLernen::Application.routes.draw do
  root to: "sessions#new"

  resources :quizzes, only: [:index]
  match 'quizzes/der_die_das', to: 'quizzes#der_die_das'#, as: 'der_die_das_quiz'
  match 'quizzes/translate_noun', to: 'quizzes#translate_noun'#, as: 'translate_noun_quiz'
  match 'quizzes/pluralise', to: 'quizzes#pluralise'
  #match 'quizzes/random_sentence', to: 'quizzes#random_sentence', as: 'random_sentence_quiz'
  

  #resources :sentences, except: :new #, only: [:index, :edit, :update, :destroy, :create]
  resources :verbs, except: [:edit]
  resources :nouns, except: [:edit]
  resources :users
  resources :password_resets, except: [:show, :delete]
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
end

app/models/verb.rb
class Verb < ActiveRecord::Base
  has_many :categories, through: :categorisations
  has_many :categorisations, as: :sentence_part, dependent: :destroy
  belongs_to :updated_by, class_name: :User
  belongs_to :created_by, class_name: :User
  belongs_to :present_tense, class_name: :Tense, dependent: :destroy
  belongs_to :infinitive, class_name: :Word, dependent: :destroy
  accepts_nested_attributes_for :infinitive, allow_destroy: true
  accepts_nested_attributes_for :present_tense, allow_destroy: true

  attr_accessible :updated_by, :created_by, :present_tense_attributes, 
                  :infinitive_attributes, :category_ids

  validates :updated_by, presence: true
  validates :created_by, presence: true
  validates :present_tense, presence: true
  validates :infinitive, presence: true
  validates :categories, presence: true

  # for removing blank values from array (useful for collection_select bug)        
  # before_validation do |verb|
  #   verb.categories.reject!(&:blank?) if verb.categories
  # end

  def self.random(n=1)
    ids = ActiveRecord::Base.connection.select_values("select id from #{self.to_s.pluralize}").sample(n)
    res = where(id: ids)
    return n == 1 ? res.first : res
  end

  def self.search(search, page)
    search_cond = "%#{search}%"
    paginate per_page: 30, page: page,
             conditions: ['words.english LIKE ? OR words.german LIKE ?', search_cond, search_cond],
             joins: :infinitive,
             order: 'english'
  end

  def infinitive_attributes=(attributes)
    self.infinitive ||= Word.new
    self.infinitive.update_attributes(attributes)
  end

  def present_tense_attributes=(attributes)
    self.present_tense ||= Tense.new
    self.present_tense.update_attributes(attributes)
  end
end

app/controllers/verbs_controller.rb
class VerbsController < ApplicationController
  before_filter :cancel_update, only: :update
  before_filter :signed_in_user
  before_filter :set_current_page
  before_filter :user_is_admin_or_creator, only: [:destroy, :edit]

  def index
    @verb = Verb.new
    @verb.infinitive = Word.new
    @verb.present_tense = Tense.new
    @search = params[:search]
    @verbs = Verb.search(@search, params[:page])
    respond_to do |format|
      format.html
    end
  end

  def show
    @verb = Verb.find(params[:id])
    @search = params[:search]
    @verbs = Verb.search(@search, params[:page])
    render action: :index
  end

  def create
    @verb = Verb.new(params[:verb])
    @verb.created_by = current_user
    @verb.updated_by = current_user

    respond_to do |format|
      if @verb.save
        format.html { redirect_to verbs_path, notice: 'Verb was successfully created.' }
      else
        format.html { 
          @verbs = Verb.paginate(page: params[:page])
          render action: :index
        }
      end
    end
  end

  def update
    @verb = Verb.find(params[:id])
    params[:verb][:updated_by] = current_user

    respond_to do |format|
      if @verb.update_attributes(params[:verb])
        format.html { redirect_to verbs_path, notice: 'Verb was successfully updated.' }
      else
        format.html { 
          @verbs = Verb.paginate(page: params[:page])
          render action: :index
        }
      end
    end
  end

  def destroy
    @verb.destroy

    respond_to do |format|
      format.html { redirect_to verbs_url }
    end
  end

  private
    def cancel_update
      redirect_to verbs_path if params[:commit] == "Cancel"
    end

    def user_is_admin_or_creator
      @verb = Verb.find(params[:id])
      current_user.admin? || @verb.created_by == current_user
    end
end

app/helpers/verbs_helper.rb
module VerbsHelper
end

app/views/verbs/_verb.html.erb
<li id="<%= verb.id %>">
  <div class="content">
    <em><%= wrap(verb.infinitive.english) %></em>
    <strong><%= wrap(verb.infinitive.german) %></strong>

    <div class="actions">
      <% if current_user.admin? %>
        <%= link_to verb_path(verb), class: "btn btn-mini btn-warning" do %>
          <i class="icon-pencil"></i> Edit
        <% end %>
      <% end %>
      <% if current_user.admin? %>
        <%= link_to verb, class: "btn btn-mini btn-danger", method: :delete, data: { confirm: "Are you sure?" } do %>
          <i class="icon-remove"></i> Delete
        <% end %>
      <% end %>
    </div>
  </div>
</li>

app/views/verbs/_verb_form.html.erb
<%= bootstrap_form_for @verb, html: { class: "form-horizontal" } do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
<!--   <%= render 'shared/german_chars' %> -->
  
  <%= f.fields_for :infinitive do |i| %>
    <%= i.text_field :english %>
    <%= i.text_field :german, label: "German (infinitive)" %>
  <% end %>

  <%= f.fields_for :present_tense do |pt| %>
    <%= pt.text_field :first_person_singular %>
    <%= pt.text_field :first_person_plural  %>
    <%= pt.text_field :second_person_informal  %>
    <%= pt.text_field :second_person_plural  %>
    <%= pt.text_field :second_person_plural_formal  %>
    <%= pt.text_field :third_person_singular  %>
    <%= pt.text_field :third_person_plural  %>
    <%= f.collection_select :category_ids, Category.all, :id, :name, { selected: @verb.categories.map(&:id) }, { multiple: true, label: "Categories" } %>
  <% end %>

  <div class="pull-right">
    <% if @verb.new_record? %>
      <%= f.submit "Create verb", class: "btn btn-primary" %>
    <% else %>
      <%= f.button "Undo", { type: :reset, class: "btn btn-success" } %>
      <%= f.submit "Cancel", class: "btn btn-danger" %>
      <%= f.submit "Save verb", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/verbs/index.html.erb
<% provide(:title, 'Verbs') %>
<div class="row">
  <aside class="span6">
    <section>
      <%= render 'verb_form' %>
    </section>
  </aside>
  <div class="span6">
    <div id="verbs">
      <%= render 'shared/search', objects: @verbs %>
      <%= render 'shared/list', objects: @verbs, partial_name: 'verb' %>
    </div>
  </div>
</div>