config/routes.rb
GermanLernen::Application.routes.draw do
  root to: "sessions#new"

  resources :quizzes, only: [:index]
  match 'quizzes/der_die_das', to: 'quizzes#der_die_das'#, as: 'der_die_das_quiz'
  match 'quizzes/translate_noun', to: 'quizzes#translate_noun'#, as: 'translate_noun_quiz'
  match 'quizzes/pluralise', to: 'quizzes#pluralise'
  #match 'quizzes/random_sentence', to: 'quizzes#random_sentence', as: 'random_sentence_quiz'
  

  #resources :sentences, except: :new #, only: [:index, :edit, :update, :destroy, :create]
  resources :verbs, except: [:edit]
  resources :nouns, except: [:edit]
  resources :users
  resources :password_resets, except: [:show, :delete]
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p class="text-center">
    Katharina and Jon are awesome!
  </p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "German Lernen", root_path, class: "brand" %>
      <nav>
        <ul class="nav pull-right">
          <% if !signed_in? %>
            <li class="divider-vertical"></li>
            <li><%= link_to "Home", root_path %></li>
          <% else %>
            <li class="divider-vertical"></li>
            <li><%= link_to "Nouns", nouns_path %></li>
            <li class="divider-vertical"></li>
            <li><%= link_to "Verbs", verbs_path %></li>
            <li class="divider-vertical"></li>
            <li><%= link_to "Quizzes", quizzes_path %></li>
            <li class="divider-vertical"></li>
            <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
            <li class="divider-vertical"></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
  	  <%= debug(params) if Rails.env.development? %>
  	  <%= debug("request method: " + request.request_method.to_s) if Rails.env.development? %>
    </div>
    
  </body>
</html>